### ISSUE TITLE
`npm install` fails

### ISSUE THREAD

**Issue by dlukes** [jupyterlab/jupyterlab_geojson#10]
I tried to set up a dev version of the extension, but `npm install` fails when compiling `src/widget.ts`:

```
src/widget.ts(22,26): error TS2497: Module '"/home/david/src/jupyterlab_geojson/node_modules/@types/lodash/isEqual/index"' resolves to a non-module entity and cannot be imported using this construct.
```

[Here's `npm-debug.log`](http://pastebin.com/KYhFtS3h).

I know little about TypeScript, but [this issue](https://github.com/Microsoft/TypeScript/issues/6656) helped me devise a workaround which seems to do the job (in the sense that `npm install` completes without errors):

```diff
diff --git a/src/widget.ts b/src/widget.ts
index 221bcc2..59ad321 100644
--- a/src/widget.ts
+++ b/src/widget.ts
@@ -19,7 +19,8 @@ import {
 
 import * as leaflet from 'leaflet';
 
-import * as isEqual from 'lodash/isEqual';
+// import * as isEqual from 'lodash/isEqual';
+var isEqual = require('lodash/isEqual');
 
 
 /**
```

But since I suppose the current code worked for you, the fix should rather be that there's a difference in my environment which has to be accounted for?

**Comment by gnestor** [comment]
The current version doesn't use Typescript so this should be resolved 👍

**Comment by dlukes** [comment]
Indeed, thanks a lot! I'm hoping to glean some inspiration from `jupyterlab_geojson` as to how to go about building a JupyterLab extension, so this is much appreciated :)

**Comment by gnestor** [comment]
@dlukes Check out https://github.com/jupyterlab/mimerender-cookiecutter. It now support both jupyterlab and notebook extensions and if you're familiar/open to use React, then creating a mimerender extension is as easy as creating a single React component.

**Comment by dlukes** [comment]
Thanks, will do!
