### ISSUE TITLE
warning / error with JupyterLab 0.12.1

### ISSUE THREAD

**Issue by dlukes** [jupyterlab/jupyterlab_geojson#11]
The [Prerequisites](https://github.com/jupyterlab/jupyterlab_geojson#prerequisites) state "JupyterLab 0.7.0 or later", but with JupyterLab 0.12.1, I get the following warning / error (?) when running both `jupyter labextension install` and `enable`:

```
X is not version compatible with installed JupyterLab version 0.12.1
    Expects JupyterLab version ^0.8.0 from packaged module jupyterlab_geojson@0.1.1/lib/plugin.js
    Expects JupyterLab version ^0.8.0 from packaged module jupyterlab_geojson@0.1.1/lib/widget.js
```

**Comment by dlukes** [comment]
Just for completeness sake: the same happens when installing the package from PyPI.

**Comment by blink1073** [comment]
@gnestor, the compatibility range should be `>=0.x, <0.x+1` for semver.

**Comment by gnestor** [comment]
@dlukes I just pushed a new version an hour ago. I've tested locally and it's working with lab 0.13.1. It looks like it has also been pushed to PyPI, but I didn't release it myself so I can't confirm.

@blink1073 Ok, so [this line](https://github.com/jupyterlab/jupyterlab_geojson/blob/master/labextension/package.json#L24) should read `"jupyterlab": ">=0.11, <0.2"`?

**Comment by dlukes** [comment]
Thanks! I can confirm the extension works both when installed from source and from PyPI, though they're probably different versions -- the PyPI one is listed as "Map" in the "Open with" menu and the map widget stretches both vertically and horizontally to fill the viewport of the pane it's in, while the source one says "GeoJSON" and its height is fixed.

**Comment by blink1073** [comment]
@gnestor, that line should say `"jupyterlab": "^0.13.1",`, which means it is compatible with `0.13.1-0.13.x` releases.  By semver rules, all `0.x` releases are major version changes.

**Comment by gnestor** [comment]
@blink1073 The issue is that `0.14` was released today (and `0.13` was released 7 days ago), so with `"jupyterlab": "^0.13.1"` this extension would already be incompatible with master. I understand that while lab is in alpha/beta, breaking API changes will happen frequently (and in minor versions). However, when lab is out of beta, it would be ideal for extensions to target major versions (e.g. `1.x`, `2.x`) and lab to reserve breaking API changes for major versions. Otherwise, I suspect that we're going to see a lot more of `X is not version compatible with installed JupyterLab version 0.x.x`.

**Comment by blink1073** [comment]
@gnestor, my point is that 0.13 -> 0.14 *is* a major version change.  We necessarily are breaking the API with each release.

**Comment by blink1073** [comment]
I realize this is causing a lot of headache for extension authors, but I do not see an alternative until we stabilize our APIs (which we are trying as hard as we can to work towards).

**Comment by blink1073** [comment]
And yes, what you propose is a sound strategy.  I will bring it up at the meeting this Friday.

**Comment by blink1073** [comment]
(Sorry if I came off as testy, this has been a source of stress for me for quite some time now).

**Comment by gnestor** [comment]
I think we are in agreement: At the moment, while in beta, breaking changes will happen constantly. After beta, breaking changes _should_ only happen with major versions. 

I'll update the current extensions and the cookiecutter to target `^0.14` and bump it on each `0.x` release.

**Comment by gnestor** [comment]
@dlukes I'll release a new version of jupyterlab_geojson to PyPI.
