### ISSUE TITLE
Double check map updating

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab_geojson#20]
When using this stuff in JupyterLab, it looks like the map may need to be updated when the notebook is resized. I think we used to have the right logic for the file viewer part of it, but not sure if that got used in the output renderer.

**Comment by ellisonbg** [comment]
Looks like there is no updating of the map view under resize events. I think the issue is that react.js doesn't know about any of that, so as long as we are using react.js it may be tough to propagate that down to react. We can talk about this and see if there is a way of getting it to work.

**Comment by gnestor** [comment]
It _appears_ to be working for me. 

![screencap](http://g.recordit.co/7nM966ipG8.gif)

**Comment by gnestor** [comment]
Now I see what you mean! Before, the map was not centering on resize. I am now passing `width` and `height` props to React (which are pushed down `onResize`) and now it looks much better:

![](http://g.recordit.co/69UfYEIBvB.gif)

**Comment by ellisonbg** [comment]
Great!
