### ISSUE TITLE
Center map when displayed

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab_geojson#22]
When a new map is dipslayed, we should center it. This was working in the file viewer, but it doesn't seem to be working in the notebook output.

@gnestor

**Comment by gnestor** [comment]
@ellisonbg It's displaying correctly for me when displaying a single coordinate. Can you provide some example GeoJSON that isn't displaying correctly?

![screencap](http://g.recordit.co/qNRiaSOcpB.gif)

**Comment by gnestor** [comment]
Closed by https://github.com/jupyterlab/jupyterlab_geojson/issues/30
