### ISSUE TITLE
Expansion to planetary bodies?

### ISSUE THREAD

**Issue by michaelaye** [jupyterlab/jupyterlab_geojson#27]
How hard would it be to expand this to other planets, most urgently Mars?
I'm a Mars surface scientist and any way to have easy Mars surface displays inside Jupyter would be awesome.
Is there a list of things that are required somewhere? Like basemaps in that format stored here, etc...

**Comment by Carreau** [comment]
Hum hum. Jupiter first. :-)

**Comment by ian-r-rose** [comment]
It should be possible, but not without a bit of work. You would need to load in a (raster) Mars tileset instead of the current Earth political tileset (something like what Google has done [here](https://www.google.com/mars/]). This would provide the underlying map layer. I am not sure where such a tileset might be found.

GeoJSON itself is a vector format, so whatever data you would be plotting on top of the map tileset would have to be convertable to that (I think that GDAL can do it for a number of formats, for instance).

**Comment by michaelaye** [comment]
@Carreau yeah, not much of a surface at Jupiter. ;)

I know where to get tilesets, they are being produced for the public by the USGS, so that's not a problem. And if there's format problems, I have colleagues there that can help out. Where can I find the Earth tileset reading/storing mechanism? I tried to browse the code to find it but can't see anything relevant?

**Comment by ian-r-rose** [comment]
The relevant link is in `component/index.js`. I was able to get a Mars tileset (mola-color) loading in the plugin by swapping it out for a link found [here](https://github.com/openplanetary/whereonmars/wiki/Basemaps). It looked like it had some alignment issues, but was a promising start. I can push a branch tomorrow as a demonstration.

**Comment by jasongrout** [comment]
I think this is really cool that someone is exploring doing Mars surface analysis in Jupyter using the leaflet plugin. I'd love to see an example notebook at some point using this.

**Comment by ian-r-rose** [comment]
[Here](https://github.com/ian-r-rose/jupyterlab_geojson/tree/mars_tileset) is a branch that swaps out the OpenStreetMap political tileset with a Martian one. The server that provides the tileset appears to be set up through [openplanetary/whereonmars](https://github.com/openplanetary/whereonmars/wiki/Basemaps).
Their wiki suggests (at least to me) that the tilesets are open, but it might be worth checking in on how they would best want to use their compute resources. Of course, you could also set up your own tile server :)

**Comment by blink1073** [comment]
Awesome sauce.

**Comment by michaelaye** [comment]
i am an admin member of OpenPlanetary, will discuss it with the guys. ;) Thanks a lot!

**Comment by michaelaye** [comment]
For some reason, the display is only working in half of the box?
<img width="1046" alt="screenshot 2017-02-10 12 55 48" src="https://cloud.githubusercontent.com/assets/69774/22841847/57d2f18a-ef90-11e6-882f-e52721d132e2.png">

EDIT: Using Safari 10.0.3 on OSX 10.11.6, Python 3.5 via conda, matplotlib 2.0

**Comment by michaelaye** [comment]
Question: Which protocols are supported via this Leaflet? Only tiled WMS? Or also traditional WMS? (I'm a WMS noob so excuse my ignorance ;) )

**Comment by gnestor** [comment]
FYI, I'm working on [an update](https://github.com/ipython/ipython/pull/10288) to the GeoJSON display class (which is [moving to ipython BTW](https://github.com/ipython/ipython/pull/10253)) that will accept additional Leaflet-specific arguments, e.g.:

```py
from IPython.display import GeoJSON

GeoJSON(data={
    "type": "Feature",
    "geometry": {
        "type": "Point",
        "coordinates": [-81.327, 296.038]
    },
    "properties": {
        "name": "Inca City"
    }
}, 
url_template="http://s3-eu-west-1.amazonaws.com/whereonmars.cartodb.net/{basemap_id}/{z}/{x}/{y}.png", 
layer_options={
    "basemap_id": "celestia_mars-shaded-16k_global",
    "attribution" : "Celestia/praesepe",
    "minZoom" : 0,
    "maxZoom" : 18,
})
```

**Comment by michaelaye** [comment]
oh, that's nice, then I can store a catalog of urls, and mix and match things! ;)

**Comment by gnestor** [comment]
Ya, the Leaflet's URL template should not be hard-coded because there are obviously so many different sources of tilesets.

**Comment by gnestor** [comment]
This is implemented with https://github.com/jupyterlab/jupyterlab_geojson/pull/30! It depends on jupyterlab@0.17.0 (or master).

![image](https://cloud.githubusercontent.com/assets/512354/23238265/f90ebfa0-f915-11e6-9fba-17928a02f6f0.png)

**Comment by gnestor** [comment]
Closed by https://github.com/jupyterlab/jupyterlab_geojson/issues/30. Give it a try!!
