### ISSUE TITLE
name `display` is not defined

### ISSUE THREAD

**Issue by michaelaye** [jupyterlab/jupyterlab_geojson#31]
Trying out #30 I'm getting this error:

<img width="1021" alt="screenshot 2017-03-01 12 11 03" src="https://cloud.githubusercontent.com/assets/69774/23476540/549d1e40-fe78-11e6-9e3b-ff30c9577c3b.png">

I use jupyterlab and jupyterlab_geojson GH master with Python 3.5 via conda-forge

**Comment by michaelaye** [comment]
I thought, maybe I need to activate the GUI loop, so I tried to do an `%matplotlib inline` beforehand but to no avail.

**Comment by gnestor** [comment]
`display` is referring to `IPython.display.display` and it looks like it's missing. I just submitted and will merge now. Thanks for catching this!!

**Comment by ocoyawale** [comment]
This solution work worked perfectly for me. I was having the same kind of issue and got an error message: "name 'display' is not defined jupyter". The suggestion by @gnestor cleared the error! Many thanks for this.
