### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by Bernat417** [jupyterlab/jupyterlab_geojson#35]
While trying to install the plugin I found the next problem:
> jupyter labextension install --symlink --py --sys-prefix jupyterlab_geojson
`Traceback (most recent call last):
  File "/usr/local/bin/jupyter-labextension", line 7, in <module>
    from jupyterlab.labextensions import main
  File "/usr/local/lib/python2.7/dist-packages/jupyterlab/labextensions.py", line 84
    [print(ext) for ext in list_extensions(self.config_dir)
         ^
SyntaxError: invalid syntax
`

Thanks in advance for any possible assistance!

**Comment by blink1073** [comment]
Hi @Bernat417, we just released 0.20.1 of JupyterLab which fixes the invalid syntax error, but this JupyterLab GeoJSON is not yet compatible with 0.20, as the extension system changed significantly.

**Comment by Bernat417** [comment]
Thanks for the quick answer @blink1073, I'll keep the eyes open for the next updates then ;)
